#Bernoulli NB Implementation
Class conditional density is calculated as   
$$ w_{jy_c} = \frac{Σ_{i=1}^n 𝟙(y^{(i)} = y_c) x_j^{(i)}}{Σ_{i=1}^n 𝟙(y^{(i)} = y_c)}
$$
* Numerator: the number of examples with label = $y_c$ and $x_j = 1$  
* Denomenator: Total no of examples with label $y_c$  

Class prior is $$ w_{jy_c} = \frac{Σ_{i=1}^n 𝟙(y^{(i)} = y_c)}{n}$$   
* Ratio of Total no of examples with label $y_c$ to total number of examples in the training set.  

While estimating the parametrs of the model, we process examples from each label separately and estimate the parameters.


In [ ]:
import numpy as np

In [ ]:
def fit(X, y):
  n_samples, n_features = X.shape
  classes = np.unique(y)
  n_classes = len(classes)

  w = np.zeros((n_classes, n_features), dtype=np.float64)
  w_priors = np.zeros(n_classes, dtype=np.float64)

  for c in range(n_features):
    x_c = X[y == c]
    w[c,:] = np.sum(x_c, axis=0)/x_c.shape[0]
    w_priors[c] = x_c.shape[0] / float(n_samples)
  
  print('weight vector: ', w)
  print('Prior: ', w_priors)
  return w, w_priors

In [ ]:
X = np.array([[1,0],[0,1],[0,1],[1,0]])
y = np.array([1,0,0,1])
fit(X, y)


weight vector:  [[0. 1.]
 [1. 0.]]
Prior:  [0.5 0.5]


(array([[0., 1.],
        [1., 0.]]), array([0.5, 0.5]))

In [ ]:
class BernoulliNB(object):
  def __init__(self, alpha=1.0):
    self.alpha = alpha
  
  def fit(self, X, y):
    n_samples, n_features = X.shape
    classes = np.unique(y)
    n_classes = len(classes)

    self.w = np.zeros((n_classes, n_features), dtype=np.float64)
    self.w_prior = np.zeros(n_classes, dtype=np.float64)
    
    for c in range(n_classes):
      X_c = X[y == c]
      self.w[c,:] = (np.sum(X_c, axis=0) + self.alpha) / (X_c.shape[0] + 2 * self.alpha)
      self.w_prior[c] = (X_c.shape[0] + self.alpha) / (float(n_samples) + n_classes * self.alpha)

    print('Class conditional density: ', self.w)
    print('Prior: ', self.w_prior)

  def log_likelyhood_prior_prod(self, X):gg
    log_likelyhood = X @ (np.log(self.w).T) + (1 - X) @ (np.log(1 - self.w).T) + np.log(self.w_prior)
    return log_likelyhood
    
  def predict_probability(self, X):
    q = self.log_likelyhood_prior_prod(X)
    #predicted_prob = np.exp(q) / np.expand_dims(np.sum(np.exp(q), axis=1), axis=1)
    predicted_prob = np.exp(q) / np.sum(np.exp(q), axis=1).reshape(-1,1)
    return predicted_prob

  def predict(self, X):
    return np.argmax(self.log_likelyhood_prior_prod(X), axis=1)
  

In [ ]:
bernoulli_nb = BernoulliNB()
X = np.array([[1,0],[0,1],[0,1],[1,0]])
y = np.array([1,0,0,1])
bernoulli_nb.fit(X, y)

Class conditional density:  [[0.25 0.75]
 [0.75 0.25]]
Prior:  [0.5 0.5]


In [ ]:
bernoulli_nb.log_likelyhood_prior_prod(X)

array([[-3.4657359 , -1.26851133],
       [-1.26851133, -3.4657359 ],
       [-1.26851133, -3.4657359 ],
       [-3.4657359 , -1.26851133]])

In [ ]:
bernoulli_nb.predict(X)

array([1, 0, 0, 1])

In [ ]:
bernoulli_nb.log_likelyhood_prior_prod(X)

array([[-3.4657359 , -1.26851133],
       [-1.26851133, -3.4657359 ],
       [-1.26851133, -3.4657359 ],
       [-3.4657359 , -1.26851133]])

In [ ]:
bernoulli_nb.predict_probability(X)

array([[0.1, 0.9],
       [0.9, 0.1],
       [0.9, 0.1],
       [0.1, 0.9]])

In [ ]:
X1 = np.array([[1,0], [0,1], [0,1], [1,0], [1,1], [1,1]])
y1 = np.array([1, 0, 0, 1, 2, 2])
b_nb = BernoulliNB()
print('fit')
print(b_nb.fit(X1, y1))
print('predict')
print(b_nb.predict(X1))
print('log likelyhood')
print(b_nb.log_likelyhood_prior_prod(X1))
print('probability')
print(b_nb.predict_probability(X1))

fit
Class conditional density:  [[0.25 0.75]
 [0.75 0.25]
 [0.75 0.75]]
Prior:  [0.33333333 0.33333333 0.33333333]
None
predict
[1 0 0 1 2 2]
log likelyhood
[[-3.87120101 -1.67397643 -2.77258872]
 [-1.67397643 -3.87120101 -2.77258872]
 [-1.67397643 -3.87120101 -2.77258872]
 [-3.87120101 -1.67397643 -2.77258872]
 [-2.77258872 -2.77258872 -1.67397643]
 [-2.77258872 -2.77258872 -1.67397643]]
probability
[[0.07692308 0.69230769 0.23076923]
 [0.69230769 0.07692308 0.23076923]
 [0.69230769 0.07692308 0.23076923]
 [0.07692308 0.69230769 0.23076923]
 [0.2        0.2        0.6       ]
 [0.2        0.2        0.6       ]]
